language: android

script:
- gradle :app123:test
- gradle :app130:test
- gradle :app131:test
- gradle :app150:test

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository

    # - sys-img-armeabi-v7a-android-15

    # Additional components
    # - extra-google-google_play_services
    # - extra-google-m2repository
    # - addon-google_apis-google-19
